services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_c_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  service-a:
    build: ./service_a
    depends_on:
      - kafka
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/service-a-db
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVICE_B_URL: http://service-b:8080
      SERVICE_B_URI: /api/process
    ports:
      - "8081:8080"

  service-b:
    build: ./service_b
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVICE_C_URL: http://service-c:8080
      SERVICE_C_URI: /api/save
    ports:
      - "8082:8080"

  service-c:
    build: ./service_c
    depends_on:
      - postgres
      - kafka
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/service_c_db
      DATASOURCE_USERNAME: user
      DATASOURCE_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8083:8080"

volumes:
  mongo_data:
  redis_data:
  postgres_data: